AboutとCoursesの作成
takuma1113/frontend-basic-site pull request #2
Opened 2023-11-23 09:29 UTC by takuma1113

画面を小さくしたときにCoursesの画像が小さくなってしまうのが、解決できませんした。

2023-11-23 17:44 UTC, JunPlayGround commented
レスポンシブ対応の際にCoursesの時に文字の配置とカードの幅が手本と異なっています
修正お願いします
※カードの幅を修正した際に、テキストの配置が少しおかしいことに気づくと思います。

ヒント
レスポンシヴ対応の際の各カードの配置・画面の端との間隔を手本と比べてみてください

2023-11-23 17:46 UTC, JunPlayGround commented
余談ですが、
手本では各カードの高さは指定されていて、あなたは指定していませんが、個人的に高さを指定した場合に「もっと見る」がはみ出てしまうので、正直今のままで大丈夫だと思います。

2023-11-24 02:21 UTC, takuma1113 commented
修正しました。
確認よろしくお願いします。

2023-11-26 18:23 UTC, JunPlayGround commented
Ground を Grand に修正だけお願いします。
見た目は大丈夫だと思います。

2023-11-27 04:53 UTC, Higashiji requested changes

2023-11-27 04:53 UTC, Higashiji commented on index.html
> +          <span class="about-title-Ground"> Ground </span>
```suggestion
          <span class="about-title-grand"> Grand </span>
```
ground → grandに修正をお願いします。
また、クラス名はケバブケースに統一するようにしましょう。
参考：https://www.wakuwakubank.com/posts/804-it-naming-convention/

2023-11-27 04:53 UTC, Higashiji commented on index.html
> +          <span class="about-title-Players"> Players</span>?
```suggestion
          <span class="about-title-players"> Players</span>?
```

2023-11-27 04:53 UTC, Higashiji commented on style.css
> +}
これは影響範囲が広いため、20行目から始まるglobalセクションに持っていったほうが見通しがよくなりそうです。

2023-11-27 04:53 UTC, Higashiji commented on style.css
> +  /* max-width: 550px; */
不要なコメントアウトは削除するようにしましょう。

2023-11-27 08:18 UTC, takuma1113 commented
修正しました。確認よろしくお願いします。

2023-11-28 14:42 UTC, higashiji2000 requested changes

2023-11-28 14:42 UTC, higashiji2000 commented on index.html
> +  <body>
> `<body>` は [HTML](https://developer.mozilla.org/ja/docs/Web/HTML) の要素で、 HTML 文書のコンテンツを示す要素です。 `<body>` 要素は文書中に一つだけ配置できます。

https://developer.mozilla.org/ja/docs/Web/HTML/Element/body

body要素が複数並んでいる状態なので、修正をお願いします 🙏 
基本的には `<html>` の直下に配置して、コンテンツ全体を囲います。

2023-11-28 14:57 UTC, higashiji2000 approved these changes
LGTM 📦

2023-11-28 15:02 UTC, merged