signup,footerの作成
takuma1113/frontend-basic-site pull request #3
Opened 2023-12-03 08:42 UTC by takuma1113

2023-12-05 14:50 UTC, JunPlayGround commented on index.html
> +              type="text"
今回は数字の入力に限定する必要があるので、`type="number"`として指定する必要があります。

2023-12-05 14:54 UTC, JunPlayGround commented on index.html
> +          <h4 class="signup-title">Let`s Try!</h4>
Let`sではなくLet'sに修正しましょう！

2023-12-05 14:57 UTC, JunPlayGround commented on style.css
> +  font-weight: 400;
手本ではもう少し字が太くなっているので、値を大きくして、手本の文字の見た目に近づけてみましょう。

2023-12-05 15:05 UTC, JunPlayGround requested changes

2023-12-05 15:05 UTC, JunPlayGround commented on style.css
> +  gap: 30px;
手本とfigmaのgapはもう少し広くなっています。
figmaや検証を使って確認してみましょう

2023-12-06 02:49 UTC, takuma1113 commented on style.css
> +  gap: 30px;
gapについての記述がfigmaの30pxしか見つからず、手本だとどこにあるかわかりませんでした。また、消しても見た目が変わらなかったので、消してしまいました。ほかの指摘された点は修正したので確認よろしくお願いします。

2023-12-06 13:22 UTC, Higashiji commented on style.css
> +}
この規模のサイトだと問題ありませんが、id セレクタと class セレクタが混在していると、詳細度の制御が難しくなる可能性があります。
なので、可能であればクラスで統一するのがベストプラクティスだと認識しています。
（修正は不要です）

2023-12-07 14:23 UTC, ssshun3 reviewed
1点だけ修正お願いします

2023-12-07 14:23 UTC, ssshun3 commented on index.html
> +            />
今回figmaの要件のところに0以上の数字のみ入力可能となっているのでマイナスの値を取らないようにお願いします。
![image](https://github.com/takuma1113/frontend-basic-site/assets/110015394/5ae5f17b-d28e-4bc0-8ad8-f20a79f0302a)

2023-12-07 15:01 UTC, ssshun3 approved these changes
LGTM!

2023-12-08 02:12 UTC, merged